// 内置精简词典：保证脚本离线/词典拉取失败时首屏也有基本汉化。
// 由 tools/make-fallback.js 从 i18n/zh-CN.json 生成，请勿手工编辑。
(function (scope) {
  'use strict';
  scope.__GHZ_FALLBACK__ = {
  "version": 0,
  "terms": {
    "Skip to content": "跳到主要内容",
    "Skip to main content": "跳到主要内容",
    "Open menu": "打开菜单",
    "Homepage": "首页",
    "Dashboard": "仪表盘",
    "Home": "首页",
    "Feed": "动态",
    "Preview": "预览",
    "Loading": "加载中",
    "Loading...": "加载中...",
    "Loading…": "加载中…",
    "Search": "搜索",
    "Search this repository": "搜索此仓库",
    "Search issues": "搜索议题",
    "Search pull requests": "搜索合并请求",
    "Search notifications": "搜索通知",
    "Type": "输入",
    "to search": "搜索",
    "Open quick search dialog, type / to search": "打开快捷搜索框，输入 / 进行搜索",
    "Chat with Copilot": "与 Copilot 对话",
    "Create new...": "新建...",
    "All issues": "所有议题",
    "All pull requests": "所有合并请求",
    "All repositories": "所有仓库",
    "Notifications": "通知",
    "Settings": "设置",
    "Appearance": "外观",
    "Accessibility": "无障碍",
    "Menu": "菜单",
    "Cancel": "取消",
    "Close": "关闭",
    "Save": "保存",
    "Saved": "已保存",
    "Done": "完成",
    "Delete": "删除",
    "Remove": "移除",
    "Edit": "编辑",
    "Add": "添加",
    "Update": "更新",
    "Create": "创建",
    "Submit": "提交",
    "Confirm": "确认",
    "Continue": "继续",
    "Previous": "上一页",
    "Next": "下一页",
    "More": "更多",
    "Learn more": "了解更多",
    "Dismiss": "忽略",
    "Clear": "清除",
    "Clear filter": "清除筛选",
    "Filter": "筛选",
    "Sort by:": "排序方式：",
    "Newest": "最新",
    "Oldest": "最旧",
    "Open": "打开",
    "Closed": "已关闭",
    "Date": "日期",
    "Repository": "仓库",
    "Language": "语言",
    "Today": "今天",
    "This week": "本周",
    "This month": "本月",
    "Code": "代码",
    "Issues": "议题",
    "Pull requests": "合并请求",
    "Pull request": "合并请求",
    "Discussions": "讨论",
    "Actions": "操作",
    "Projects": "项目",
    "Wiki": "Wiki",
    "Security": "安全",
    "Insights": "洞察",
    "Watch": "关注",
    "Star": "收藏",
    "Unstar": "取消收藏",
    "Starred": "已收藏",
    "Fork": "Fork",
    "Sponsor": "赞助",
    "About": "关于",
    "Releases": "发行版",
    "Packages": "软件包",
    "Contributors": "贡献者",
    "Latest commit": "最新提交",
    "Branches": "分支",
    "Tags": "标签",
    "Go to file": "跳转到文件",
    "Add file": "添加文件",
    "History": "历史",
    "Name": "名称",
    "Activity": "活动",
    "Owner": "所有者",
    "Author": "作者",
    "Assignees": "负责人",
    "Labels": "标签",
    "Milestones": "里程碑",
    "New issue": "新建议题",
    "New pull request": "新建合并请求",
    "Terms": "条款",
    "Privacy": "隐私",
    "Status": "状态",
    "Community": "社区",
    "Docs": "文档",
    "Contact": "联系我们",
    "Manage cookies": "管理 Cookie",
    "Switch repository": "切换仓库",
    "Open in github.dev": "在 github.dev 中打开",
    "Open in codespace": "在 Codespace 中打开",
    "See your forks of this repository": "查看你 Fork 的此仓库副本",
    "View all files": "查看全部文件",
    "Assigned to me": "分配给我的",
    "Created by me": "我创建的",
    "Mentioned": "提到我的",
    "Views": "浏览量",
    "Reviews": "评审",
    "Review required": "需要评审",
    "Approved": "已批准",
    "Comment": "评论",
    "Reply": "回复",
    "Watchers": "关注者",
    "Contributing": "贡献指南",
    "Code of conduct": "行为准则",
    "Security policy": "安全策略",
    "License": "许可证",
    "Topics": "主题",
    "New repository": "新建仓库",
    "Create a new repository": "创建新仓库",
    "Create repository": "创建仓库",
    "Repository name": "仓库名称",
    "Description": "描述",
    "Configuration": "配置",
    "Public": "公开",
    "Private": "私有",
    "Advanced": "高级",
    "Advanced search": "高级搜索",
    "Sign in": "登录",
    "Sign out": "退出登录",
    "Sign up": "注册",
    "Overview": "概览",
    "Profile": "个人资料",
    "Account": "账号",
    "Inbox": "收件箱",
    "Mark all read notifications as done": "将所有已读通知标记为完成",
    "Collapse sidebar": "收起侧边栏",
    "Add new filter": "添加新的筛选器",
    "Newest to oldest": "从新到旧",
    "Oldest to newest": "从旧到新",
    "Notifications by date": "按日期显示的通知",
    "Clear out the clutter.": "清理杂物。",
    "Resources": "资源",
    "Readme": "说明文档",
    "Deployments": "部署",
    "Stargazers": "收藏者",
    "Report repository": "举报仓库",
    "Latest": "最新",
    "Commit changes": "提交更改",
    "You have no unread notifications": "你没有未读通知",
    "Open user navigation menu": "打开用户导航菜单",
    "Dismiss alert": "关闭提示",
    "No results found": "没有找到结果",
    "Retry": "重试",
    "Copy": "复制",
    "Copied": "已复制",
    "Unsubscribe": "取消订阅",
    "Subscribe": "订阅",
    "Mark as read": "标记为已读",
    "Followers": "关注者",
    "Contributing guidelines": "贡献指南",
    "Good first issues": "适合新贡献者的议题"
  },
  "phrases": [
    {
      "pattern": "^([\\d,.kKmM]+)\\s+Commits$",
      "flags": "",
      "replacement": "$1 次提交"
    },
    {
      "pattern": "^([\\d,.kKmM]+)\\s+commits?$",
      "flags": "i",
      "replacement": "$1 次提交"
    },
    {
      "pattern": "^([\\d,.kKmM]+)\\s+reactions$",
      "flags": "",
      "replacement": "$1 个回应"
    },
    {
      "pattern": "^([\\d,.kKmM]+)\\s+people reacted$",
      "flags": "",
      "replacement": "$1 人回应"
    },
    {
      "pattern": "^([\\d,.kKmM]+)\\s+stars today$",
      "flags": "",
      "replacement": "今日新增 $1 收藏"
    },
    {
      "pattern": "^([\\d,.kKmM+]+)\\s+results?$",
      "flags": "",
      "replacement": "$1 个结果"
    },
    {
      "pattern": "results?\\s*$",
      "flags": "",
      "replacement": "个结果"
    },
    {
      "pattern": "Updated\\s+(.+)$",
      "flags": "",
      "replacement": "更新于 $1"
    },
    {
      "pattern": "^0\\s+results$",
      "flags": "",
      "replacement": "0 个结果"
    }
  ]
};
})(typeof unsafeWindow !== 'undefined' ? unsafeWindow : window);
